name: CI

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Use npm install instead of npm ci because
      # package.json and package-lock.json are currently
      # not synchronized.
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v5

      - name: Start Nx Cloud CI
        run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"

      - name: Run Nx tasks
        run: npx nx affected -t lint test build typecheck e2e

      - name: Fix CI
        if: always()
        run: npx nx fix-ci
